# Generated by Django 4.1 on 2023-02-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('description', models.TextField(null=True)),
                ('avatar', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('id_comment_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallapop.ad')),
                ('id_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallapop.user')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='id_ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallapop.user'),
        ),
    ]
