# Generated by Django 4.1 on 2023-03-15 07:30

import Wallapop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallapop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(null=True, upload_to=Wallapop.models.ads_directory),
        ),
    ]
