# Generated by Django 4.1 on 2023-03-15 08:37

import Wallapop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallapop', '0002_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to=Wallapop.models.ads_directory),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to=Wallapop.models.user_directory_path),
        ),
    ]
