# Generated by Django 4.2 on 2023-05-17 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wallapop', '0005_ad_created_at_alter_comment_id_comment_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
